easy_admin:
  
  site_name: 'PHP Web'
  
  list:
    item_permission: 'ROLE_ADMIN'
  new:
    item_permission: 'ROLE_ADMIN'
  edit:
    item_permission: 'ROLE_ADMIN'
  
  design:
    menu:
      - label: 'Posts'
        icon: blog
        children:
          - { entity: 'Post', icon: 'list', label: 'Post' , permission: 'ROLE_EDITOR', default: true }
          - { entity: 'Tags', label: 'Tags', icon: 'tag', permission: 'ROLE_ADMIN'}
          - { entity: 'ImagePost', label: 'Imagenes', icon: 'image', permission: 'ROLE_EDITOR'}
          - { entity: 'Comment', label: 'Comentarios', icon: 'comment', permission: 'ROLE_EDITOR'}
      - { entity: 'User', icon: 'user', label: 'Usuarios', permission: 'ROLE_ADMIN'}
      - { label: 'Regresar a la pagina', route: 'home', icon: home }
  
  entities:
    User:
      class: App\Entity\User
      image_base_path: '/images/'
      list:
        fields:
          - { property: 'id'}
          - { property: 'username'}
          - { property: 'email'}
          - { property: 'roles'}
          - { property: 'gender'}
          - { property: 'location'}
          - { property: 'avatar', type: 'image'}
      form:
        fields:
          - {type: section, label: 'Avatar'}
          - {property: avatar}
          - {type: section, label: 'Informacion obligatoria'}
          - {property: username}
          - {property: plainPassword, label: 'Contraseña', type: password, type_options: { required: true }}
          - {property: email, type: email}
          - {type: section, label: 'Informacion Opcional'}
          - {property: gender, type: 'choice', type_options: { expanded: false, multiple: false, choices: { 'Hombre': 'Hombre', 'Mujer': 'Mujer'}}}
          - {property: location}
          - {property: information, type: textarea}
          - {type: section, label: 'Role en la pagina'}
          - {property: roles, 
              type: 'choice', 
              type_options: { 
                expanded: true, 
                multiple: true, 
                choices: { 
                  'Administrador': 'ROLE_ADMIN', 
                  'Editor': 'ROLE_EDITOR', 
                  'Usuario normal': 'ROLE_USER'
                }
              }
            }
      edit:
        fields:
          - {property: 'plainPassword', label: 'Contraseña', type: 'password', type_options: { required: false } }
    Post:
      class: App\Entity\Post
      templates:
        list: 'admin/Models/EDITOR_list.html.twig'
      list:
        item_permission: 'ROLE_EDITOR'
        fields:
          - {property: id}
          - {property: title, label: 'Titulo'}
          - {property: usuario, label: 'Usuario'}
          - {property: post_date, label: 'Creacion'}
          - {property: post_modified, label: 'Modificado'}
          - {property: tags, label: 'Tags'}
          - {property: comments, label: 'Comentarios'}

      form:
        item_permission: 'ROLE_EDITOR'
        fields:
          - {property: title, type: text, label: 'Titulo'}
          - {property: post_text, type: textarea, label: 'Contenido'}
          - {property: tags, type_options:{required: true, by_reference: false}}
    
    Tags:
      class: App\Entity\Tags
    
    ImagePost:
      class: App\Entity\ImagePost
      templates:
        list: 'admin/Models/EDITOR_list.html.twig'
      new:
        item_permission: 'ROLE_EDITOR'
      edit:
        item_permission: 'ROLE_EDITOR'
    
    Comment:
      class: App\Entity\Comment
      list:
        item_permission: 'ROLE_EDITOR'
      new:
        item_permission: 'ROLE_EDITOR'
      edit:
        item_permission: 'ROLE_EDITOR'